debug = true

[[nodes]]
host            = "wss://ws.t0rn.io"
parachain_id    = 3333
sleep_time_secs = 1

[[subscribers]]
host            = "wss://ws.t0rn.io"
parachain_id    = 3333
sleep_time_secs = 5

[[subscribers.listener_events]]
module  = "System"
variant = "ExtrinsicFailed"

[[subscribers]]
host            = "wss://rococo-rpc.polkadot.io"
parachain_id    = 1
sleep_time_secs = 5

[[subscribers.listener_events]]
module  = "Ump"
variant = "ExecutedUpward"
