debug = true

[[nodes]]
host            = "ws://localhost:2222"
parachain_id    = 2
sleep_time_secs = 1

[[nodes]]
host            = "ws://localhost:3333"
parachain_id    = 3
sleep_time_secs = 1

[[subscribers]]
host            = "ws://localhost:2222"
parachain_id    = 2
sleep_time_secs = 5

[[subscribers.listener_events]]
module  = "System"
variant = "ExtrinsicFailed"

[[subscribers]]
host            = "ws://localhost:3333"
parachain_id    = 3
sleep_time_secs = 5

[[subscribers.listener_events]]
module  = "System"
variant = "ExtrinsicFailed"

[[subscribers]]
host            = "ws://localhost:9944"
parachain_id    = 1
sleep_time_secs = 5

[[subscribers.listener_events]]
module  = "Ump"
variant = "ExecutedUpward"
