debug = true

[[nodes]]
parachain_id = 2
host = "ws://localhost:2222"
sleep_time_secs = 1

[[nodes]]
parachain_id = 3
host = "ws://localhost:3333"
sleep_time_secs = 1

[[subscribers]]
parachain_id = 2
host = "ws://localhost:2222"
sleep_time_secs = 5

[[subscribers.listener_events]]
module = "System"
variant = "ExtrinsicFailed"

[[subscribers]]
parachain_id = 3
host = "ws://localhost:3333"
sleep_time_secs = 5

[[subscribers.listener_events]]
module = "System"
variant = "ExtrinsicFailed"

[[subscribers]]
parachain_id = 1
host = "ws://localhost:9944"
sleep_time_secs = 5

[[subscribers.listener_events]]
module = "Ump"
variant = "ExecutedUpward"