[workspace]
#members = [ "crates/*", 'pallets/portal', 'pallets/asset-registry', "integration-test" ] # FIXME: put this back  "client"
members = [ "crates/*", 'pallets/portal', 'pallets/asset-registry'] # FIXME: put this back  "client"
