name: Comment Release Version to PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "**/*.rs"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - .github/workflows/comment_version_on_pr.yml
    branches:
      - "main"

jobs:
  comment-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Next Version
        id: version
        uses: paulhatch/semantic-version@v5.0.2
        with:
          tag_prefix: "v"
          major_pattern: "/feat!:|refactor!:"
          major_regexp_flags: "g"
          minor_pattern: "/feat:|refactor:"
          minor_regexp_flags: "g"
          version_format: "${major}.${minor}.${patch}"
          bump_each_commit: false
          search_commit_body: false
          user_format_type: "json"
          enable_prerelease_mode: true
      - name: Comment on PR with version
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            Hey, the version for this pull request will be: ${{ steps.version.outputs.version }}
          message-id: pr
          reactions: rocket
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
