name: Pull request workflow

on:
  pull_request:
    paths:
      - "**/*.rs"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - .github/workflows/pull_request.yml
  push:
    branches:
      - main
      - development
    paths:
      - "**/*.rs"
      - "**/Cargo.*"
      - .github/workflows/pull_request.yml
env:
  RUST_BACKTRACE: 1

jobs:
  check-rust:
    runs-on: self-hosted
    steps:
      - name: ☁️Checkout git repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}

      - name: ⚙️Get nightly rust toolchain with wasm target
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: clippy, rustfmt, llvm-tools-preview
          override: true

      - name: 📜 Lint code format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Install clippy-sarif
        uses: baptiste0928/cargo-install@v1
        with:
          crate: clippy-sarif

      - name: Install sarif-fmt
        uses: baptiste0928/cargo-install@v1
        with:
          crate: sarif-fmt

      - name: 📑 Lint code
        run: cargo clippy --all-targets --all-features --message-format=json | clippy-sarif | tee results.sarif | sarif-fmt

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

      - name: Install nextest
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest

      - name: Install cargo-llvm-cov
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-llvm-cov

      - name: 📑 Test workspace and collect coverage data
        uses: actions-rs/cargo@v1
        with:
          command: llvm-cov
          args: nextest --workspace --lcov --output-path lcov.info

      - name: Upload coverage data
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info

      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: lcov.info
