name: Semantic Version

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  calculate:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Calculate semantic version
        id: version
        uses: paulhatch/semantic-version@v5.0.2
        with:
          tag_prefix: "v"
          major_pattern: "/^((feat)|(refactor))(\\([a-z]+\\))?!:/"
          minor_pattern: "/^((feat)|(refactor))(\\([a-z]+\\))?:/"
          version_format: "${major}.${minor}.${patch}"
          bump_each_commit: false
          search_commit_body: false
          user_format_type: "json"

      - name: Comment Next Tag
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ### :sparkles: Next version based on commits in this PR
            ##  ${{ steps.version.outputs.version_tag }}
          message-id: semantic-version-${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
